### PR TITLE
Add Accessory Store

### PR DESCRIPTION
**Pull request by RealMoondancer**
Added new Tab for Accessory Store and added support for Kingdom Credit currency

### CODE REVIEW

**Comment by RealMoondancer** [comment]
Just realised I forgot to add kingdom credits to the profile overview for the currencies

**Comment by vascYT** [comment]
Did you use [Prettier](https://prettier.io/) for formatting? If not it would be nice if you do to keep the formatting consistent.

**Comment by RealMoondancer** [comment]
I think it used the defaut JetBrains formatting, but I tried to keep it consistant manually

**Comment by vascYT** [comment]
Okay, I will probably add prettier to the dev dependencies, so you can run something like `pnpm format` and it formats all the code automatically. Maybe even a commit hook to do it automatically.

If you could format it with prettier manually, that would be great!

**Comment by RealMoondancer** [comment]
Will do once I get out of school

**Comment by RealMoondancer** [comment]
Added it, it should work but I couldn't test it yet since I'm not home atm

**Comment by RealMoondancer** [comment]
Successfully tested the Profile view and added the needed translation keys to en.json

**Comment by RealMoondancer** [comment]
Any update on this @vascYT ?

**Comment by vascYT** [comment]
> Any update on this @vascYT ?

The PR looks good to me 👍
I am ready to merge it, but I am not sure about the 5 additional requests that are sent when launching the app (see my comment above). I figure its not possible to remove them as these are all the assets for the accessory store, but just wanted to hear your opinion on it before merging.

**Comment by RealMoondancer** [comment]
Yea, it add a pretty noticeable delay when launching the app.

I recently saw a question in the discord if one could lower the quality of the streamed videos and we may be able to eliminate these requests and lower the video quality if we were to add a separate server for these requests.

But other than that I can't really see an option to remove them

**Comment by vascYT** [comment]
But this is out of the scope of this PR, so I will merge it for now 👍 Thanks again for your contribution.

**Pull request merged**
